services:
  mst-app:
    container_name: master-application
    build:
      context: ..
      dockerfile: application/Dockerfile
    env_file: .env
    ports:
      - 80:80
    tty: true
    depends_on:
      - db

  dev-app:
    container_name: develop-application
    build:
      context: ..
      dockerfile: application/Dockerfile
    env_file: .env
    ports:
      - 8080:80
    tty: true
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:16.2
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "spring_boot_template"
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
    networks:
      fixed_network:
        ipv4_address: 172.18.0.2

networks:
  fixed_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
