services:
  app:
    container_name: application
    build:
      context: ..
      dockerfile: application/Dockerfile
    env_file: .env
    networks:
      - fixed_network
    ports:
      - 80:80
    tty: true
    depends_on:
      db:
        condition: service_healthy

  db:
    container_name: database
    image: postgres:16.2
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "playground"
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
    networks:
      fixed_network:
        ipv4_address: 172.18.0.2
    healthcheck:
      test: [ "CMD", "pg_isready", "-U", "postgres" ]
      start_period: 10s
      interval: 1s
      retries: 60
      timeout: 5s

networks:
  fixed_network:
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/16
