version: 2
updates:
  - package-ecosystem: 'gradle'
    directory: 'application'
    schedule:
      interval: 'daily'
    target-branch: 'master'
    reviewers:
      - 'ORIKAMIxNEP'
    assignees:
      - 'ORIKAMIxNEP'
