services:
  application:
    container_name: application
    build:
      dockerfile: application/Dockerfile
    env_file: .env
    tty: true
    depends_on:
      - database
    ports:
      - 8080:8080

  database:
    container_name: database
    image: postgres:16.2
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "spring_boot_template"
    volumes:
      - ./database/initdb:/docker-entrypoint-initdb.d
    ports:
      - "5432:5432"
