services:
  application:
    container_name: application
    build:
      dockerfile: docker/application/Dockerfile
      args:
        CSRF_TOKEN: $CSRF_TOKEN
    env_file: application/.env
    tty: true
    depends_on:
      - database
    ports:
      - 8080:8080

  database:
    container_name: database
    image: postgres:16.2
    environment:
      POSTGRES_USER: "postgres"
      POSTGRES_PASSWORD: "postgres"
      POSTGRES_DB: "spring_boot_template"
    volumes:
      - ./docker/database/initdb:/docker-entrypoint-initdb.d
