services:
  app:
    container_name: application
    build:
      context: ..
      dockerfile: application/Dockerfile
    env_file: .env
    ports:
      - 8080:8080
    tty: true
    depends_on:
      - db

  db:
    container_name: database
    image: postgres:16.2
    env_file: .env
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: "spring_boot_template"
    volumes:
      - ../database/initdb:/docker-entrypoint-initdb.d
    networks:
      fixed_network:
        ipv4_address: 172.18.0.2

  web:
    container_name: web-server
    image: nginx:1.27.0
    volumes:
      - ../web-server/config/default.conf:/etc/nginx/conf.d/default.conf
    ports:
      - 80:80
    depends_on:
      - app

networks:
  fixed_network:
    driver: bridge
    ipam:
      driver: default
      config:
        - subnet: 172.18.0.0/24
