spring:
  application:
    name: spring_boot_template
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/spring_boot_template
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
server:
  port: 8080
