spring:
  application:
    name: playground
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://database:5432/playground
    username: ${POSTGRES_USER}
    password: ${POSTGRES_PASSWORD}
  jpa:
    properties:
      hibernate:
        dialect: org.hibernate.dialect.PostgreSQLDialect
server:
  port: 80
