### AddRecord
POST http://localhost:8080/record
Content-Type: application/json
X-CSRF-TOKEN: test

{
  "column1": 0,
  "column2": "a"
}

### FetchRecord
GET http://localhost:8080/record/1
X-CSRF-TOKEN: test

### UpdateRecord
PUT http://localhost:8080/record
Content-Type: application/json
X-CSRF-TOKEN: test

{
  "recordId": 1,
  "column1": 0,
  "column2": "a"
}

### DeleteRecord
DELETE http://localhost:8080/record
Content-Type: application/json
X-CSRF-TOKEN: test

{
  "recordId": 1
}
