### AddRecord
POST http://localhost:8080/record
X-CSRF-TOKEN: test

### FetchRecord
GET http://localhost:8080/record
X-CSRF-TOKEN: test

### UpdateRecord
PUT http://localhost:8080/record
X-CSRF-TOKEN: test

### UpdateRecordRecord1
PATCH http://localhost:8080/record
X-CSRF-TOKEN: test

### DeleteRecord
DELETE http://localhost:8080/record
X-CSRF-TOKEN: test
