### AddTask
POST {{baseUrl}}/project/0100ABCDEFGHJKMNPQRSTVWXYZ/task
Content-Type: application/json

{
  "taskName": "TaskName3"
}

### FetchTask
GET {{baseUrl}}/project/0100ABCDEFGHJKMNPQRSTVWXYZ/task/0200ABCDEFGHJKMNPQRSTVWXYZ

### UpdateTask
PUT {{baseUrl}}/project/0100ABCDEFGHJKMNPQRSTVWXYZ/task/0200ABCDEFGHJKMNPQRSTVWXYZ
Content-Type: application/json

{
  "taskName": "UpdatedTaskName",
  "assignedAccountIds": [
    "0000ABCDEFGHJKMNPQRSTVWXYZ"
  ]
}

### AdvanceStatus
PUT {{baseUrl}}/project/0100ABCDEFGHJKMNPQRSTVWXYZ/task/0200ABCDEFGHJKMNPQRSTVWXYZ/status
Content-Type: application/json

### DeleteTask
DELETE {{baseUrl}}/project/0100ABCDEFGHJKMNPQRSTVWXYZ/task/0200ABCDEFGHJKMNPQRSTVWXYZ
