### AddTask
POST {{baseUrl}}/task
Content-Type: application/json

{
  "column1": 0,
  "column2": "a"
}

### FetchTask
GET {{baseUrl}}/task/0123456789ABCDEFGHJKMNPQRS

### UpdateTask
PUT {{baseUrl}}/task
Content-Type: application/json

{
  "taskId": "0123456789ABCDEFGHJKMNPQRS",
  "column1": 0,
  "column2": "a"
}

### DeleteTask
DELETE {{baseUrl}}/task
Content-Type: application/json

{
  "taskId": "0123456789ABCDEFGHJKMNPQRS"
}
