### AddTask
POST {{baseUrl}}/project/1123456789ABCDEFGHJKMNPQRS/task
Content-Type: application/json

{
  "taskName": "TaskName"
}

### FetchTask
GET {{baseUrl}}/project/1123456789ABCDEFGHJKMNPQRS/task/2123456789ABCDEFGHJKMNPQRS

### UpdateTask
PUT {{baseUrl}}/project/1123456789ABCDEFGHJKMNPQRS/task/2123456789ABCDEFGHJKMNPQRS
Content-Type: application/json

{
  "taskName": "UpdatedTaskName"
}

### AdvanceStatus
PUT {{baseUrl}}/project/1123456789ABCDEFGHJKMNPQRS/task/2123456789ABCDEFGHJKMNPQRS/status
Content-Type: application/json

### DeleteTask
DELETE {{baseUrl}}/project/1123456789ABCDEFGHJKMNPQRS/task/2123456789ABCDEFGHJKMNPQRS
