@startuml
package "Spring Boot Template" {
  entity accounts {
    * account_id: VARCHAR(26)
    --
    * account_name: TEXT
    * password: TEXT
  }

  entity projects {
    * project_id: VARCHAR(26)
    --
    * project_name: TEXT
  }

  entity project_participation {
    * project_id: VARCHAR(26)
    * participating_account_id: VARCHAR(26)
    --
  }

  accounts ||--o{ project_participation
  projects ||--|{ project_participation

  entity tasks {
    * task_id: VARCHAR(26)
    * in_project_id: VARCHAR(26)
    --
    * task_name: TEXT
    * status: TEXT
    * index: INTEGER
  }

  projects ||--o{ tasks

  entity task_assignment {
    * task_id: VARCHAR(26)
    * assigned_account_id: VARCHAR(26)
    --
  }

  accounts ||--o{ task_assignment: "1" - "0..10"
  tasks ||--o{ task_assignment

  entity task_due_date {
    in_task_id: VARCHAR(26)
    due_date: TIMESTAMP
    postpone_count: INTEGER
    max_postpone_count: INTEGER
  }

  tasks ||--|| task_due_date
}
@enduml
